"""
Main interface module to use pyEPR.

Contains code to connect to Ansys and to analyze HFSS files using the EPR method.

This module handles the microwave part of the analysis and connection to

Further contains code to be able to do autogenerated reports,

Copyright Zlatko Minev, Zaki Leghtas, and the pyEPR team
2015, 2016, 2017, 2018, 2019, 2020
"""
# pylint: disable=invalid-name, unused-import


from .project_info import ProjectInfo
from .core_quantum_analysis import QuantumAnalysis
from .core_distributed_analysis import DistributedAnalysis

_DEPRECATED_ALIASES = {
    "Project_Info": ProjectInfo,
    "pyEPR_HFSSAnalysis": DistributedAnalysis,
    "pyEPR_Analysis": QuantumAnalysis,
}

_NEW_NAMES = {
    "Project_Info": "ProjectInfo",
    "pyEPR_HFSSAnalysis": "DistributedAnalysis",
    "pyEPR_Analysis": "QuantumAnalysis",
}


def __getattr__(name):
    if name in _DEPRECATED_ALIASES:
        import warnings
        warnings.warn(
            f"pyEPR.core.{name} is deprecated and will be removed in a future release. "
            f"Use pyEPR.core.{_NEW_NAMES[name]} instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        return _DEPRECATED_ALIASES[name]
    raise AttributeError(f"module 'pyEPR.core' has no attribute {name!r}")
