name: CI

on:
  push:
    branches:
      - master
  pull_request: ~
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run pylint
        run: uv run --group dev pylint --errors-only --jobs=0 pyEPR

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.9.27
      - name: Run tests
        run: uv run --group dev --python ${{ matrix.python-version }} pytest

  test_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.9.27
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Make docs
        run: |
          cd docs
          uv run --group docs make html
      - name: Upload docs to artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docs
          path: docs/build/html/
          retention-days: 5
